---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

How doth the little crocodile  
Improve his shining tail,  
And pour the waters of the Nile  
On every golden scale!   

How cheerfully he seems to grin  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
To be, or not to be: that is the question:  
Whether ’tis nobler in the mind to suffer  
The slings and arrows of outrageous fortune,    
Or to take arms against a sea of troubles,   
And by opposing end them? To die: to sleep;    
No more; and by a sleep to say we end  
The heart-ache and the thousand natural shocks  
That flesh is heir to, ’tis a consummation  
Devoutly to be wish’d. To die, to sleep;  
To sleep: perchance to dream: ay, there’s the rub;  
For in that sleep of death what dreams may come  
When we have shuffled off this mortal coil,  
Must give us pause: there’s the respect  
That makes calamity of so long life;  
